language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

before_deploy:
  - yarn global add surge
  - gridsome build

deploy:
  provider: script
  script: yarn deploy
  on:
    branch: master