language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

before_deploy:
  - gridsome build

deploy:
  provider: surge
  project: ./dist/
  domain: ruten-basketball.surge.sh
  skip_cleanup: true